In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import cv2
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import tensorflow as tf
from tensorflow.keras import layers, models
from plotly.subplots import make_subplots
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense
from tensorflow.keras.models import Model
from PIL import Image
import plotly.offline as pyo
from IPython.display import display
# import torch
# import torchvision
# import torchvision.transforms as transforms
# import torch.nn as nn
# import torch.optim as optim
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report
from keras.models import Sequential
from keras.preprocessing.image import ImageDataGenerator

from tensorflow.keras import datasets, layers, models


In [19]:
kaggle_info = {
    "username": "user_kaggle",
    "key": "api_key"
}

In [4]:
# Install the Kaggle library
!pip install -q kaggle

# Set Kaggle credentials
import json
import os

# Replace the following with your Kaggle username and API key


# Save Kaggle credentials to a JSON file
os.makedirs("/root/.kaggle", exist_ok=True)
with open("/root/.kaggle/kaggle.json", "w") as file:
    json.dump(kaggle_info, file)

# Change the permissions of the file
!chmod 600 /root/.kaggle/kaggle.json

# Download the dataset
!kaggle datasets download -d likhon148/animal-data
# Unzip the dataset
#!mkdir /content/gpiosenka/sports-classification
!unzip -q animal-data.zip -d animal-data

# List the contents of the directory
!ls /content/animal-data


 94% 34.0M/36.3M [00:00<00:00, 150MB/s] 
100% 36.3M/36.3M [00:00<00:00, 137MB/s]
animal_data


In [12]:
import os
#numpydata = np.array(img)

# Dictionary to store files with labels
train_images = {}
path = "/content/animal-data/animal_data/Bear"

# Iterate over files in the directory
for file_name in os.listdir(path):
    # Check if current item is a file
    if os.path.isfile(os.path.join(path, file_name)):
        # Add filename and label to the dictionary
        train_images[file_name] = '0'

print(train_images)


{'Bear_28.jpg': '0', 'bear_1_3.jpg': '0', 'Bear_30_3.jpg': '0', 'Bear_16.jpeg': '0', 'Bear_24_2.jpg': '0', 'Bear_2_1.jpg': '0', 'Bear_13_4.jpg': '0', 'Bear_20_3.jpg': '0', 'bear_4_3.jpg': '0', 'Bear_17_1.jpg': '0', 'Bear_3.jpg': '0', 'Bear_28_1.jpg': '0', 'Bear_5.jpeg': '0', 'Bear_26_3.jpg': '0', 'Bear_25_1.jpg': '0', 'Bear_6_1.jpg': '0', 'Bear_7_3.jpg': '0', 'Bear_10_1.jpg': '0', 'bear_8_2.jpg': '0', 'Bear_9_1.jpg': '0', 'Bear_12.jpeg': '0', 'Bear_27_1.jpg': '0', 'Bear_10_3.jpg': '0', 'Bear_17_3.jpg': '0', 'bear_8_3.jpg': '0', 'Bear_3_1.jpg': '0', 'Bear_7.jpeg': '0', 'Bear_18.jpeg': '0', 'Bear_9_4.jpg': '0', 'Bear_20_4.jpg': '0', 'Bear_16_1.jpg': '0', 'Bear_24_3.jpg': '0', 'Bear_9_2.jpg': '0', 'Bear_22_2.jpg': '0', 'Bear_6_2.jpg': '0', 'Bear_16_2.jpg': '0', 'Bear_2.jpeg': '0', 'Bear_23_2.jpg': '0', 'Bear_29_1.jpg': '0', 'Bear_14_1.jpg': '0', 'Bear_27_2.jpg': '0', 'Bear_24_1.jpg': '0', 'Bear_11.jpeg': '0', 'Bear_15_3.jpg': '0', 'Bear_12_1.jpg': '0', 'bear_4_4.jpg': '0', 'Bear_5_1.jpg':

In [23]:
import os
#numpydata = np.array(img)

# Dictionary to store files with labels
train_images = []
path = "/content/animal-data/animal_data/Bear"

# Iterate over files in the directory
for file_name in os.listdir(path):
    # Check if current item is a file
    if os.path.isfile(os.path.join(path, file_name)):
        # Add filename and label to the dictionary
        #train_images[file_name] = '0'
        train_images = np.array(file_name)


print(train_images)


Bear_19_1.jpg


In [24]:
train_images

array('Bear_19_1.jpg', dtype='<U13')

In [47]:
import os
import cv2
import numpy as np
#my_tuple = np.array((1, 2, 3, 4, 5))
train_labels = []
train_images = []
path = "/content/animal-data/animal_data/Bear"

# Iterate over files in the directory
for file_name in os.listdir(path):
    # Check if current item is a file
    if os.path.isfile(os.path.join(path, file_name)):
        # Read the image
        image = cv2.imread(os.path.join(path, file_name))
        # Convert the image to a numpy array
        if image is not None:
            image = image / 255.0 # Normalize pixel values to be between 0 and 1
            train_images.append(np.array(image))
            train_labels.append(np.array("0"))
        else:
            print(f"Unable to read image: {file_name}")

# Convert the list of images to a numpy array
train_images_array = np.array(train_images)
train_labels = np.array(train_labels)

print(train_images_array,train_labels)
#print(train_labels)



[[[[0.96470588 0.7254902  0.46666667]
   [0.96078431 0.72156863 0.4627451 ]
   [0.95686275 0.71764706 0.45882353]
   ...
   [0.99607843 0.83529412 0.64313725]
   [0.99607843 0.83137255 0.64705882]
   [0.99607843 0.83137255 0.64705882]]

  [[0.96470588 0.7254902  0.46666667]
   [0.96078431 0.72156863 0.4627451 ]
   [0.96078431 0.72156863 0.4627451 ]
   ...
   [0.99607843 0.83529412 0.64313725]
   [0.99607843 0.83137255 0.64705882]
   [0.99607843 0.83137255 0.64705882]]

  [[0.96862745 0.72941176 0.47058824]
   [0.96470588 0.7254902  0.46666667]
   [0.96470588 0.7254902  0.46666667]
   ...
   [0.99607843 0.83137255 0.64705882]
   [0.99607843 0.83137255 0.64705882]
   [0.99607843 0.83137255 0.64705882]]

  ...

  [[0.25490196 0.20392157 0.14117647]
   [0.29803922 0.25098039 0.18039216]
   [0.38039216 0.32156863 0.24705882]
   ...
   [0.20784314 0.11764706 0.03137255]
   [0.13333333 0.0745098  0.01176471]
   [0.24313725 0.20784314 0.15686275]]

  [[0.56078431 0.52156863 0.45098039]
   [0.4

In [44]:
type(train_images_array)


numpy.ndarray

In [43]:
type(train_labels)

numpy.ndarray